name: CI/CD Pipeline tru

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-verify-docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: peter7100/crypto-app
      IMAGE_TAG: 1.0

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      # 3. Set up Maven
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      # 4. Build the project
      - name: Build with Maven
        run: mvn clean package

      # 5. Run OpenJML verification
      - name: OpenJML Verification
        run: |
          rm -rf OpenJML OpenJML.zip
          
          wget https://github.com/OpenJML/OpenJML/releases/download/21-0.19/openjml-ubuntu-22.04-21-0.19.zip -O OpenJML1.zip
          unzip OpenJML1.zip -d OpenJML1
          
          
          echo "$PWD/OpenJML/bin" >> $GITHUB_PATH
         
      # 6. Log in to DockerHub using secrets
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Build Docker image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # 8. Push Docker image
      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG
